// Generated via https://github.com/jeremyrsellars/slate-cljs-walkthroughs#closure-externs
// from NPM

// Reference ns as SlateReact
/**********************************************************************
 * Extern for SlateReact
 * Generated by https://github.com/jeremyrsellars/slate-cljs-walkthroughs#closure-externs
 **********************************************************************/
var SlateReact = {
    "DefaultElement": function() {},
    "DefaultLeaf": function() {},
    "Editable": function() {},
    "ReactEditor": {
        "blur": function() {},
        "deselect": function() {},
        "findEventRange": function() {},
        "findKey": function() {},
        "findPath": function() {},
        "focus": function() {},
        "hasDOMNode": function() {},
        "insertData": function() {},
        "isFocused": function() {},
        "isReadOnly": function() {},
        "toDOMNode": function() {},
        "toDOMPoint": function() {},
        "toDOMRange": function() {},
        "toSlateNode": function() {},
        "toSlatePoint": function() {},
        "toSlateRange": function() {},
    },
    "Slate": function() {},
    "useEditor": function() {},
    "useFocused": function() {},
    "useReadOnly": function() {},
    "useSelected": function() {},
    "useSlate": function() {},
    "withReact": function() {},
};
